(cl:in-package #:model-info-generator)

(defmethod emit ((element data-model) (format t) (target pathname))
  (assert (uiop:directory-pathname-p target))
  (ensure-directories-exist target)
  (a:maphash-values
   (lambda (element)
     (when (output? element)
       (let* ((name       (name element))
              (filename   (filename<-omop-table format name))
              (type       (string-downcase format))
              (filename   (make-pathname :name filename :type type))
              (pathname   (merge-pathnames filename target)))
         (emit element format pathname))))
   (tables element)))

(defmethod emit ((element table) (format t) (target pathname))
  (a:with-output-to-file (stream target :if-exists :supersede)
    (pprint-logical-block (stream (list element))
      (emit element format stream))))
