(cl:in-package #:model-info-generator)

(defmethod canonical-concept-column ((table table))
  (if (equal (name table) "concept")
      (find-column "concept_id" table)
      (let ((candidates '()))
        (mapc (lambda (column)
                (let ((name   (name column))
                      (suffix "_concept_id"))
                  (when (a:ends-with-subseq suffix name)
                    (let ((stem (subseq name 0 (- (length name) (length suffix)))))
                      (push (cons stem column) candidates)))))
              (columns table))
        (flet ((for-name (name)
                 (a:assoc-value candidates name :test #'string=)))
          (let ((table-name (name table))
                (suffix     "_occurrence"))
            (or (for-name table-name)
                (when (a:ends-with-subseq suffix table-name)
                  (for-name (subseq table-name 0 (- (length table-name) (length suffix)))))))))))
